//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALISIS_REACTIVO
    {
        public int id_analisis_reactivo { get; set; }
        public int id_reactivo { get; set; }
        public decimal cantidad { get; set; }
        public byte id_unidad { get; set; }
        public int id_analisis_empleado { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual ANALISIS_EMPLEADO ANALISIS_EMPLEADO { get; set; }
        public virtual REACTIVO REACTIVO { get; set; }
        public virtual UNIDAD UNIDAD { get; set; }
    }
}
