//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA
    {
        public AREA()
        {
            this.ANALISIS = new HashSet<ANALISI>();
            this.EMPLEADOes = new HashSet<EMPLEADO>();
        }
    
        public byte id_area { get; set; }
        public string nombre_area { get; set; }
    
        public virtual ICollection<ANALISI> ANALISIS { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADOes { get; set; }
    }
}
