//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALCULO
    {
        public CALCULO()
        {
            this.INPUTs = new HashSet<INPUT>();
        }
    
        public int id_calculo { get; set; }
        public int id_analisis_empleado { get; set; }
        public int id_resultado { get; set; }
        public decimal resultado_calculo { get; set; }
    
        public virtual ANALISIS_EMPLEADO ANALISIS_EMPLEADO { get; set; }
        public virtual RESULTADO RESULTADO { get; set; }
        public virtual ICollection<INPUT> INPUTs { get; set; }
    }
}
