//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_VISITA
    {
        public int id_detalle_visita { get; set; }
        public int id_visita { get; set; }
        public int id_muestra { get; set; }
        public Nullable<decimal> value { get; set; }
    
        public virtual MUESTRA MUESTRA { get; set; }
        public virtual VISITA VISITA { get; set; }
    }
}
