//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_SOLICITUD
    {
        public DETALLE_SOLICITUD()
        {
            this.ANALISIS_EMPLEADO = new HashSet<ANALISIS_EMPLEADO>();
        }
    
        public int id_detalle_solicitud { get; set; }
        public int id_solicitud { get; set; }
        public int id_analisis { get; set; }
    
        public virtual ANALISI ANALISI { get; set; }
        public virtual ICollection<ANALISIS_EMPLEADO> ANALISIS_EMPLEADO { get; set; }
        public virtual SOLICITUD SOLICITUD { get; set; }
    }
}
