//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXISTENCIA_SOLUCION
    {
        public EXISTENCIA_SOLUCION()
        {
            this.SALIDA_SOLUCION = new HashSet<SALIDA_SOLUCION>();
        }
    
        public int id_existencia_solucion { get; set; }
        public byte id_empleado { get; set; }
        public int id_solucion { get; set; }
        public decimal cantidad { get; set; }
        public byte id_unidad { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual SOLUCION SOLUCION { get; set; }
        public virtual ICollection<SALIDA_SOLUCION> SALIDA_SOLUCION { get; set; }
    }
}
