//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    
    public partial class GRUPO_SOLICITUD
    {
        public GRUPO_SOLICITUD()
        {
            this.VISITAs = new HashSet<VISITA>();
        }
    
        public int id_grupo_solicitud { get; set; }
        public int id_solicitante { get; set; }

        [DataType(DataType.DateTime), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha_solicitud { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string preset { get; set; }
        public string identificador { get; set; }
    
        public virtual SOLICITANTE SOLICITANTE { get; set; }
        public virtual ICollection<VISITA> VISITAs { get; set; }
    }
}
