//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME
    {
        public int id_informe { get; set; }
        public int id_solicitud { get; set; }
        public string tipo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string data { get; set; }
        public byte activo { get; set; }
        public string areas { get; set; }
    
        public virtual SOLICITUD SOLICITUD { get; set; }
    }
}
