//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPUT
    {
        public int id_input { get; set; }
        public int id_variable { get; set; }
        public int id_calculo { get; set; }
        public decimal valor { get; set; }
        public string lectura { get; set; }
    
        public virtual CALCULO CALCULO { get; set; }
        public virtual VARIABLE VARIABLE { get; set; }
    }
}
