//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIMITE
    {
        public string analisis { get; set; }
        public Nullable<int> id_analisis { get; set; }
        public string unidades { get; set; }
        public Nullable<decimal> incerteza { get; set; }
        public Nullable<decimal> limite_deteccion { get; set; }
    }
}
