//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MARNEntities : DbContext
    {
        public MARNEntities()
            : base("name=MARNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALMACEN> ALMACENs { get; set; }
        public virtual DbSet<ANALISI> ANALISIS { get; set; }
        public virtual DbSet<ANALISIS_EMPLEADO> ANALISIS_EMPLEADO { get; set; }
        public virtual DbSet<AREA> AREAs { get; set; }
        public virtual DbSet<CALCULO> CALCULOes { get; set; }
        public virtual DbSet<CATALOGO> CATALOGOes { get; set; }
        public virtual DbSet<DETALLE_SOLICITUD> DETALLE_SOLICITUD { get; set; }
        public virtual DbSet<DETALLE_VISITA> DETALLE_VISITA { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<ESTADO> ESTADOes { get; set; }
        public virtual DbSet<ESTADO_PROCESO> ESTADO_PROCESO { get; set; }
        public virtual DbSet<EXISTENCIA_PRODUCTO> EXISTENCIA_PRODUCTO { get; set; }
        public virtual DbSet<EXISTENCIA_SOLUCION> EXISTENCIA_SOLUCION { get; set; }
        public virtual DbSet<INPUT> INPUTs { get; set; }
        public virtual DbSet<LOTE> LOTEs { get; set; }
        public virtual DbSet<MARCA> MARCAs { get; set; }
        public virtual DbSet<MUESTRA> MUESTRAs { get; set; }
        public virtual DbSet<PROCEDENCIA> PROCEDENCIAs { get; set; }
        public virtual DbSet<PROCESO_ANALISTA> PROCESO_ANALISTA { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public virtual DbSet<REACTIVO> REACTIVOes { get; set; }
        public virtual DbSet<REACTIVO_SOLUCION> REACTIVO_SOLUCION { get; set; }
        public virtual DbSet<REPORTE> REPORTEs { get; set; }
        public virtual DbSet<RESULTADO> RESULTADOes { get; set; }
        public virtual DbSet<SALIDA_EXISTENCIA> SALIDA_EXISTENCIA { get; set; }
        public virtual DbSet<SALIDA_SOLUCION> SALIDA_SOLUCION { get; set; }
        public virtual DbSet<SOLICITANTE> SOLICITANTEs { get; set; }
        public virtual DbSet<SOLICITUD> SOLICITUDs { get; set; }
        public virtual DbSet<SOLUCION> SOLUCIONs { get; set; }
        public virtual DbSet<TIPO_EMPLEADO> TIPO_EMPLEADO { get; set; }
        public virtual DbSet<TIPO_MUESTRA> TIPO_MUESTRA { get; set; }
        public virtual DbSet<TIPO_VARIABLE> TIPO_VARIABLE { get; set; }
        public virtual DbSet<UNIDAD> UNIDADs { get; set; }
        public virtual DbSet<VARIABLE> VARIABLEs { get; set; }
        public virtual DbSet<VISITA> VISITAs { get; set; }
        public virtual DbSet<ESTADO_PROCESO_ANALISTA> ESTADO_PROCESO_ANALISTA { get; set; }
        public virtual DbSet<INFORME> INFORMES { get; set; }
        public virtual DbSet<NOTIFICACION> NOTIFICACIONs { get; set; }
        public virtual DbSet<ANALISIS_REACTIVO> ANALISIS_REACTIVO { get; set; }
        public virtual DbSet<SITIO_MUESTREO> SITIO_MUESTREO { get; set; }
        public virtual DbSet<GRUPO_SOLICITUD> GRUPO_SOLICITUD { get; set; }
        public virtual DbSet<LIMITE> LIMITES { get; set; }
    }
}
