//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE
    {
        public int id_reporte { get; set; }
        public int id_analisis_empleado { get; set; }
        public Nullable<decimal> resultado { get; set; }
        public Nullable<decimal> incerteza { get; set; }
        public string unidades { get; set; }
        public Nullable<decimal> limite_deteccion { get; set; }
        public string metodo { get; set; }
        public string comentario { get; set; }
    
        public virtual ANALISIS_EMPLEADO ANALISIS_EMPLEADO { get; set; }
    }
}
