//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioMarn
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDAD
    {
        public UNIDAD()
        {
            this.PRODUCTOes = new HashSet<PRODUCTO>();
            this.REACTIVO_SOLUCION = new HashSet<REACTIVO_SOLUCION>();
            this.SALIDA_EXISTENCIA = new HashSet<SALIDA_EXISTENCIA>();
            this.ANALISIS_REACTIVO = new HashSet<ANALISIS_REACTIVO>();
        }
    
        public byte id_unidad { get; set; }
        public string nombre { get; set; }
        public string unidad1 { get; set; }
        public string equivalencia { get; set; }
    
        public virtual ICollection<PRODUCTO> PRODUCTOes { get; set; }
        public virtual ICollection<REACTIVO_SOLUCION> REACTIVO_SOLUCION { get; set; }
        public virtual ICollection<SALIDA_EXISTENCIA> SALIDA_EXISTENCIA { get; set; }
        public virtual ICollection<ANALISIS_REACTIVO> ANALISIS_REACTIVO { get; set; }
    }
}
